site_name: "pilot-signbridge"
site_description: "Pilot-SignBridge. Secure digital signatures in your browser"
dev_addr: "127.0.0.1:8080"
repo_url: "https://github.com/pilotextensions/pilot-signbridge"
site_url: "https://pilotextensions.github.io/pilot-signbridge"
theme:
  name: shadcn
  icon: heroicons:check-badge
  show_stargazers: false
  pygments_style:
    light: shadcn-light
    dark: github-dark
  katex_options:
    macros:
      "\\dx": "\\mathrm{d}x"
  # show_datetime: true

# nav:
#   - Home: index.md 
#   - Check Extension: check-extension.md
#   - API:
#       - Global: api/global.md
#       - Certificate: api/certificate.md
#       - Verification Response: api/verification.md
#       - Verification Status: api/verificationstatus.md

markdown_extensions:
  codehilite:
  extra:
  admonition:
